### ISSUE TITLE
meteor-shell.js never gets created

### ISSUE THREAD

**Issue by kodie** [qualialabs/prod-shell#2]
I'm using `meteor@1.8.0.2`, `mup@1.4.5`, and `qualia:prod-shell@0.0.3`. After I run `mup deploy` and then SSH into my server as `root` (which is the same user Meteor is running on), there's no `~/meteor-shell.js` file.

Running `find / -name "meteor-shell.js"` on the server returns this:
```
/var/lib/docker/overlay2/caede23a6e1f840847c7ae7a17eef67dce0e77b64a09421189ac39e715ec94fd/merged/root/meteor-shell.js
/var/lib/docker/overlay2/caede23a6e1f840847c7ae7a17eef67dce0e77b64a09421189ac39e715ec94fd/diff/root/meteor-shell.js
```

and executing either one of those files simply returns `Server unavailable (waiting to reconnect)`.

If I copy the contents of `shell_client.js` to `~/meteor-shell.js` and then execute it, I get this:
```
path.js:28
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.join (path.js:1236:7)
    at getInfoFile (/root/meteor-shell.js:17:15)
    at Client.connect (/root/meteor-shell.js:52:18)
    at Object.<anonymous> (/root/meteor-shell.js:190:42)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

Any help would be appreciated.

**Comment by jamesgibson14** [comment]
Did anyone every find a solution to this, I can't figure it out? I am getting the same issue when deploying with `mup` and a non root user.

**Comment by kodie** [comment]
@jamesgibson14 Nope I never did get it working regardless if I was logged in as root or not. My only workaround was to connect the local version of my app to the production database and run commands from local so that I could run functions that do things to the production db.
